version: '3.1'

services:
    zoomysql:
        image: mysql:5.7
        restart: always
        working_dir: /app
        container_name: 'zoomysql'
        environment:
            MYSQL_ROOT_PASSWORD: zoo_pass
            MYSQL_DATABASE: zoo
            MYSQL_USER: zoo_user
            MYSQL_PASSWORD: zoo_pass_user
        ports:
            - 15432:3306
        expose:
            - 15432
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        networks:
            - app-network

    php-fpm:
        build: docker
        container_name: 'php'
        ports:
            - 9000:9000
        volumes:
            - ./:/app
        working_dir: /app
        networks:
            - app-network

    nginx:
        image: nginx
        container_name: 'nginx'
        working_dir: /app
        ports:
            - 7777:80
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        networks:
            - app-network


networks:
    app-network:
        driver: bridge


volumes:
    db_data: {}
    dump: {}